# 테스트 환경 설정
spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/blogfy_test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false